### ISSUE TITLE
Unable to build image on m2 pro

### ISSUE THREAD

**Issue by nkroker** [moritzheiber/ruby-jemalloc-docker#15]
### Issue
> **Facing issues while building the `ruby-3.1.4-jemalloc`**

### System Config
**OS:** MacOS Sonoma 14.1.2
**Chip:** Apple M2 Pro
**Docker version:** 20.10.22, build 3a2c30b

### Screenshots
![Screenshot 2023-12-14 at 12 43 57 AM](https://github.com/moritzheiber/ruby-jemalloc-docker/assets/26537166/ce28361d-81d8-4494-94db-3925e80876e9)

### Shell Traces
[Debug-trace.txt](https://github.com/moritzheiber/ruby-jemalloc-docker/files/13664726/Debug-trace.txt)

**Comment by moritzheiber** [comment]
Hey @nkroker, thank you for your report. I tracked down the failing build to a checksum error (line 599/600 in your `Debug-trace.txt`; thanks for supplying that btw, much appreciated!). It looks like you're passing a checksum when building the image manually (good!) but I think you caught the wrong checksum in the `index.txt` ( :disappointed: ). The checksum you're passing (`1b6d6010e76036c937b9671f4752f065aeca800a6c664f71f6c9a699453af94f`) matches the file `https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.4.tar.xz` (mind the **xz** at the end) and not the file `https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.4.tar.gz` (**tar.gz** at the end; its checksum is `a3d55879a0dfab1d7141fdf10d22a07dbf8e5cdc4415da1bde06127d5cc3c7b6`).

May I suggest you try building the image again using the matching checksum and report back? I'm using the `tar.gz` packages because `tar` is a more common format.

PS: You can always use the [`ruby-version-checker`](https://github.com/moritzheiber/ruby-version-checker-rs) container to fetch the latest available Ruby releases and their corresponding checksums:

```console
$ docker run ghcr.io/moritzheiber/ruby-version-checker
# [...]
[
  {
    "name": "3.0.6",
    "url": "https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.6.tar.gz",
    "sha256": "6e6cbd490030d7910c0ff20edefab4294dfcd1046f0f8f47f78b597987ac683e"
  },
  {
    "name": "3.1.4",
    "url": "https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.4.tar.gz",
    "sha256": "a3d55879a0dfab1d7141fdf10d22a07dbf8e5cdc4415da1bde06127d5cc3c7b6"
  },
  {
    "name": "3.2.2",
    "url": "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz",
    "sha256": "96c57558871a6748de5bc9f274e93f4b5aad06cd8f37befa0e8d94e7b8a423bc"
  }
]
```

**Comment by moritzheiber** [comment]
I've also added a clarification to the relevant paragraph in the README (22e53b4861768a8702febf8954de2929120274c1)

**Comment by nkroker** [comment]
Thankyou @moritzheiber,

You saved me, your suggestion worked like a charm and the image was built successfully. 🎉 

![Screenshot 2023-12-14 at 1 33 42 AM](https://github.com/moritzheiber/ruby-jemalloc-docker/assets/26537166/11c074e7-b09f-4ac5-9319-85217cd14712)
